README.md, make_argocd_fly/application.py, tests/manual/config.yml, tests/manual/source/app_2/base/kustomization.yml, tests/manual/source/app_2/external_1/kustomization.yml, tests/manual/source/app_2/management/kustomization.yml
=> Use plain kustomize

make_argocd_fly/application.py, make_argocd_fly/main.py
misc: add cli option to presenve tmp directory
=> Store tmp files in unique directories

make_argocd_fly/application.py, make_argocd_fly/log_config.yml, make_argocd_fly/main.py
=> Introduce debug logging

.github/workflows/pypi-publish.yml, .github/workflows/tests-run.yml, README.md, dev_requirements.txt, make_argocd_fly/main.py, tests/test_resource.py
feat: remove only relevant applications output directories
feat: introduce --clean cli parameter to remove all output directories
misc: update workflow/actions
fix: pytests
=> Introduce more control on applications output directories cleanup

.gitignore, make_argocd_fly/config.py, make_argocd_fly/main.py, tests/manual/config.yml, tests/test_config.py
misc: configure work directories via cli params
fix: config-file and root-dir params passed together
=> Configure work directories

make_argocd_fly/application.py
misc: add simple retry mechanism for kustomize run
=> Retry kustomize execution

make_argocd_fly/application.py, make_argocd_fly/config.py, make_argocd_fly/main.py
misc: log app/env on kustomize error
misc: adjust log levels
=> Log app/env on kustomize failures

make_argocd_fly/application.py, make_argocd_fly/cli_args.py, make_argocd_fly/config.py, make_argocd_fly/main.py, tests/test_config.py
feat: print application variable with --print-vars cli param
misc: centralize cli arguments
=> Add --print-vars cli parameter

README.md, make_argocd_fly/application.py, tests/manual/config.yml, tests/test_utils.py
=> Introduce app_name and env_name variables

make_argocd_fly/main.py, make_argocd_fly/utils.py
fix: logging updated applications
=> Check if version of make_argocd_fly is the latest available

tests/manual/config.yml, tests/manual/output/management/app_12/deployment_grafana.yml, tests/manual/source/app_12/deployment.yml.j2
ArgoCD independent applications already work. Added an example. Documentation will be done separately.
=> Add argocd independent manual app test

README.md, dev_requirements.txt, make_argocd_fly/application.py, make_argocd_fly/renderer.py, make_argocd_fly/steps.py, pyproject.toml, tests/manual/config.yml, tests/test_steps.py
=> Consolidate argocd variables

README.md, make_argocd_fly/application.py, make_argocd_fly/cli_args.py, make_argocd_fly/main.py, make_argocd_fly/resource.py, make_argocd_fly/steps.py, make_argocd_fly/utils.py
misc: remove old code
misc: introduce `--remove-output-dir` parameter
=> Remove --clean parameter and make it default behavior

README.md, make_argocd_fly/config.py, make_argocd_fly/log_config.yml, make_argocd_fly/renderer.py, make_argocd_fly/utils.py, tests/manual/output/management/app_15/configmap_prometheus-config.yml, tests/manual/output/management/app_16/configmap_prometheus-config.yml, tests/test_renderer.py
misc: configure package logger instead of root logger
=> Sort files included in a template by filename

make_argocd_fly/application.py, make_argocd_fly/config.py, make_argocd_fly/consts.py, make_argocd_fly/exceptions.py, make_argocd_fly/main.py, make_argocd_fly/params.py, make_argocd_fly/resource.py, make_argocd_fly/utils.py, pyproject.toml, tests/test_config.py, tests/test_params.py, tests/test_resource.py, tests/test_steps.py, tests/test_utils.py
feat: harden config class
misc: introduce config keywork constants
misc: simplify params class
misc: fix pytest warning
=> Introduce custom exception hierarchy

make_argocd_fly/config.py, make_argocd_fly/exceptions.py, make_argocd_fly/main.py, make_argocd_fly/renderer.py, make_argocd_fly/resource.py, make_argocd_fly/steps.py, make_argocd_fly/utils.py, tests/test_config.py, tests/test_renderer.py, tests/test_resource.py, tests/test_steps.py, tests/test_utils.py
misc: extend custom exceptions hierarchy
misc: detect Jinja2 undefined variables
misc: simplify main function
=> Gracefully handle internal exceptions

make_argocd_fly/application.py, make_argocd_fly/config.py, make_argocd_fly/exceptions.py, make_argocd_fly/log_config.yml, make_argocd_fly/main.py, make_argocd_fly/renderer.py, make_argocd_fly/resource.py, make_argocd_fly/steps.py, make_argocd_fly/utils.py, make_argocd_fly/warnings.py, tests/test_renderer.py, tests/test_resource.py, tests/test_steps.py, tests/test_utils.py
misc: convert .format() to f-strings
=> Improve kustomize error reporting

docs/examples.md, make_argocd_fly/main.py, make_argocd_fly/steps.py
=> Improve examples docs

make_argocd_fly/config.py, make_argocd_fly/renderer.py, make_argocd_fly/resource/viewer.py, make_argocd_fly/resource/writer.py, make_argocd_fly/step.py, make_argocd_fly/util.py, tests/test_renderer.py, tests/test_resource.py
misc: remove old get_children functionality
=> Unilize viewer search_subresources functionality

make_argocd_fly/application.py, make_argocd_fly/exception.py, make_argocd_fly/main.py, make_argocd_fly/resource/data.py, make_argocd_fly/resource/persistence.py, make_argocd_fly/step.py, tests/test_resource.py, tests/test_step.py
misc: introduce output resource context
misc: move yaml creation to resource writer class
=> Extract output filename generation logic to a separate step

make_argocd_fly/cliparam.py, make_argocd_fly/config.py, make_argocd_fly/default.py, make_argocd_fly/main.py, make_argocd_fly/param.py, make_argocd_fly/pipeline.py, make_argocd_fly/resource/persistence.py, make_argocd_fly/resource/type.py, make_argocd_fly/stage.py, make_argocd_fly/util.py, tests/test_config.py, tests/test_param.py, tests/test_pipeline.py, tests/test_resource.py, tests/test_stage.py
misc: refactor default values
misc: use string enums
misc: improve error messages
=> Add app_type application parameter

make_argocd_fly/config.py, make_argocd_fly/main.py, make_argocd_fly/param.py, make_argocd_fly/pipeline.py, make_argocd_fly/resource/writer.py, make_argocd_fly/stage.py, tests/test_pipeline.py, tests/test_resource.py
misc: select writer based on app type and file type
misc: deterministic data ordering
misc: add exponential backoff for kustomize retries
=> Gracefully handle ExceptionGroup exception
